- name: Install pipx
  run: |
    python -m pip install --upgrade pip
    pip install pipx
    pipx ensurepath

- name: Install Snowflake CLI (pipx)
  run: |
    pipx install snowflake-cli
    snow --help
